//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace solutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("solutions.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11223
        ///6323
        ///10725
        ///10761
        ///3587
        ///
        ///1274
        ///1041
        ///5566
        ///1759
        ///1372
        ///1619
        ///2228
        ///1283
        ///1981
        ///1885
        ///5894
        ///1321
        ///6081
        ///4407
        ///2992
        ///
        ///7184
        ///2310
        ///7975
        ///2752
        ///7942
        ///7616
        ///3622
        ///1320
        ///1231
        ///6191
        ///
        ///3069
        ///10691
        ///4789
        ///5329
        ///6726
        ///9550
        ///6188
        ///3117
        ///
        ///17492
        ///3489
        ///18055
        ///
        ///12369
        ///21123
        ///
        ///2121
        ///5065
        ///5377
        ///1768
        ///6060
        ///1256
        ///1496
        ///6899
        ///3569
        ///3766
        ///6873
        ///5490
        ///2961
        ///
        ///6407
        ///3770
        ///2823
        ///5998
        ///7783
        ///4194
        ///1866
        ///5504
        ///6550
        ///7857
        ///2884
        ///
        ///5385
        ///4621
        ///2434
        ///6123
        ///2159
        ///6191
        ///3552
        ///6871
        ///
        ///6531
        ///4287
        ///7402
        ///5634
        ///3960
        ///
        ///4955 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Y
        ///A Y
        ///B X
        ///A Y
        ///C Y
        ///B Y
        ///B Z
        ///B Y
        ///A X
        ///B X
        ///C Z
        ///B Y
        ///B Y
        ///B Y
        ///B Y
        ///C X
        ///A Z
        ///B X
        ///A Y
        ///A Y
        ///B Y
        ///A X
        ///C X
        ///B Y
        ///A Y
        ///B Y
        ///C X
        ///A Z
        ///B Y
        ///A X
        ///A Y
        ///B Y
        ///A Y
        ///A X
        ///B Y
        ///B Y
        ///B Y
        ///B X
        ///A X
        ///C Y
        ///A X
        ///C Z
        ///B Z
        ///A Z
        ///A Z
        ///C X
        ///A X
        ///A X
        ///B Y
        ///B Y
        ///C Y
        ///B Y
        ///B X
        ///B Y
        ///B Y
        ///B X
        ///C X
        ///A X
        ///A X
        ///A Z
        ///C X
        ///A Z
        ///A X
        ///B Y
        ///B Y
        ///A Y
        ///A Z
        ///B Y
        ///B X
        ///B Y
        ///B Y
        ///B X
        ///C Z
        ///A X
        ///B X
        ///B X
        ///A Y
        ///B X
        ///C Z
        ///B Y
        ///A X
        ///C Z
        ///A Y
        ///B Y
        ///B Y
        ///A X
        ///A Z
        ///B Y
        ///B Y
        ///A Z
        ///A Z
        ///B Y
        ///A X
        ///A Z
        ///C Y
        ///A X
        ///B Y
        ///C X
        ///A X
        ///B Y
        ///A X
        ///A Z
        ///C  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sfDRhjhHsHhgWPJvPmmQnmPqnW
        ///pTddGVwcpMTTCdnQJqqQqqqVtVms
        ///MdZCZGdcrCNRFZRhFssL
        ///CttWnSnNfSnCHsWrTlTPPpPCTRrLpl
        ///DgqqghjqJBVgDMTPGVlRGwbfLLGP
        ///cgqBBhjqcBdMcWQcQNnNzsfv
        ///lnDWMgTLlTFlHHgDDgngWFnlBWNcBQrdjcrrdQrPBrdjhWhj
        ///JqSVRRVmmRqJJbZGGJqJvbmBNcjPNQNssQPhSSdwPwwwQr
        ///bCRJqGJJmzmJZRCmFNTLTttTzfFfLglf
        ///SPWvWMvCSPcjzjDbcwfjTl
        ///lLNRNLqhhQVQJlRjrjrDwTzzqzzfrb
        ///GRnRVhRJLFnnhtJQNVdLdLgWCmmZlMlgSCSWSgpZtPBM
        ///pTGFrLFTFWFprLDBmLbSbtmBDb
        ///MqjwqJwZlqJjHlqjHHPmSbsffDmsStDnHnQmsm
        ///ZPJjVPZbVMRRPZwMJZVMNJMcGWpWFcWFFNFGrWTzWz [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 98-99,3-97
        ///23-72,23-72
        ///53-62,8-87
        ///21-52,36-51
        ///36-38,37-96
        ///92-96,4-92
        ///7-30,8-60
        ///31-44,43-88
        ///67-73,45-73
        ///37-48,49-62
        ///32-50,1-33
        ///39-98,38-47
        ///11-17,18-88
        ///35-99,36-97
        ///9-82,2-3
        ///27-50,4-10
        ///1-92,5-92
        ///6-40,4-40
        ///4-7,2-3
        ///98-99,46-96
        ///24-38,23-39
        ///5-88,5-87
        ///12-97,12-96
        ///19-37,18-37
        ///14-39,14-85
        ///25-55,24-45
        ///30-92,31-92
        ///49-61,50-79
        ///4-69,4-70
        ///29-37,29-42
        ///12-77,11-79
        ///2-2,4-86
        ///55-55,54-54
        ///55-80,81-86
        ///8-10,7-8
        ///52-92,42-54
        ///32-63,32-55
        ///3-83,2-83
        ///97-97,8-97
        ///13-87,86-90
        ///43-95,42-43
        ///39-96,39-8 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
    }
}
